import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#f8fafc" },
    scrollView: { flex: 1 },
    scrollContent: { paddingBottom: 120 },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 24,
        paddingTop: 48,
        paddingBottom: 24,
        backgroundColor: "#f8fafc",
    },
    headerSubtitle: {
        fontSize: 12,
        fontWeight: "700",
        color: "#94a3b8",
        letterSpacing: 1,
        marginBottom: 4,
    },
    headerTitle: { fontSize: 24, fontWeight: "800", color: "#1e293b", letterSpacing: 1 },
    profileImageContainer: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: "#fff",
        borderWidth: 2,
        borderColor: "#fff",
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    profileImage: {
        width: "100%",
        height: "100%",
    },
    avatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        borderWidth: 2,
        borderColor: "#fff",
    },
    heroCard: {
        marginHorizontal: 16,
        borderRadius: 32,
        padding: 24,
        marginBottom: 32,
        overflow: "hidden",
    },
    heroDecor1: {
        position: "absolute",
        top: -40,
        right: -40,
        width: 160,
        height: 160,
        backgroundColor: "rgba(255,255,255,0.1)",
        borderRadius: 80,
    },
    heroDecor2: {
        position: "absolute",
        bottom: 0,
        right: 80,
        width: 96,
        height: 96,
        backgroundColor: "rgba(236,72,153,0.2)",
        borderRadius: 48,
    },
    heroContent: { zIndex: 10 },
    priorityBadge: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255,255,255,0.2)",
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 16,
        alignSelf: "flex-start",
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.1)",
    },
    priorityText: {
        color: "#fff",
        fontSize: 10,
        fontWeight: "700",
        marginLeft: 4,
        letterSpacing: 1,
    },
    heroTitle: {
        fontSize: 28,
        fontWeight: "700",
        color: "#fff",
        marginBottom: 8,
    },
    heroDescription: {
        fontSize: 16,
        color: "rgba(255,255,255,0.9)",
        fontWeight: "500",
        marginBottom: 16,
        lineHeight: 24,
    },
    heroHighlight: {
        fontWeight: "700",
        backgroundColor: "rgba(255,255,255,0.2)",
        paddingHorizontal: 4,
        borderRadius: 4,
    },
    heroAvatars: { flexDirection: "row", marginBottom: 24 },
    avatarAlert: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: "rgba(255,255,255,0.2)",
        borderWidth: 2,
        borderColor: "#a855f7",
        justifyContent: "center",
        alignItems: "center",
        marginRight: -8,
    },
    avatarAlertText: { color: "#fff", fontWeight: "700", fontSize: 12 },
    avatarCount: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: "#fff",
        borderWidth: 2,
        borderColor: "#a855f7",
        justifyContent: "center",
        alignItems: "center",
    },
    avatarCountText: { color: "#8b5cf6", fontWeight: "700", fontSize: 10 },
    heroButton: {
        backgroundColor: "#fff",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    heroButtonText: {
        color: "#8b5cf6",
        fontSize: 16,
        fontWeight: "700",
        marginRight: 8,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 32,
        paddingBottom: 16,
    },
    sectionTitle: { fontSize: 20, fontWeight: "800", color: "#1e293b" },
    getQuoteButton: {
        backgroundColor: '#181818',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    getQuoteButtonText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    businessCard: {
        backgroundColor: "#fff",
        borderRadius: 24,
        marginHorizontal: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "#f1f5f9",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    businessHeader: {
        padding: 20,
    },
    businessHeaderTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 4,
    },
    businessName: {
        fontSize: 16,
        fontWeight: "700",
        color: "#1e293b",
        flex: 1,
        marginRight: 16,
    },
    businessAddressText: {
        fontSize: 13,
        color: "#64748b",
        fontWeight: "500",
        marginBottom: 16,
    },
    businessHeaderBottom: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    businessIcons: {
        flexDirection: "row",
        alignItems: "center",
    },
    addButton: {
        justifyContent: "center",
        alignItems: "center",
    },
    contractsContainer: {
        paddingHorizontal: 20,
        paddingBottom: 16,
    },
    contractRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
        backgroundColor: "#fff",
    },
    contractLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 16,
        flex: 1,
    },
    iconContainer: {
        width: 44,
        height: 44,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
    },
    contractFuel: { fontSize: 15, fontWeight: "700", color: "#1e293b", marginBottom: 2 },
    contractDays: { fontSize: 13, fontWeight: "600" },
    contractRight: { flexDirection: "row", alignItems: "center" },
    emptyContracts: { padding: 16, alignItems: "center" },
    emptyContractsText: { fontSize: 14, color: "#cbd5e1" },
    fab: {
        position: 'absolute',
        bottom: 24,
        right: 24,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#ff5a5f',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
        zIndex: 999,
    },
    sheetBackground: {
        backgroundColor: "#fff",
        borderTopLeftRadius: 40,
        borderTopRightRadius: 40,
    },
    sheetIndicator: {
        backgroundColor: "#cbd5e1",
        width: 40,
        height: 4,
    },
    sheetHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 24,
        paddingTop: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f8fafc",
    },
    sheetTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "#1e293b",
        flex: 1,
        textAlign: "center",
    },
    backButton: {
        width: 32,
        height: 32,
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 8,
    },
    sheetClose: {
        width: 32,
        height: 32,
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
    },
    sheetBody: {
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 40,
    },
    modalDescription: {
        color: "#64748b",
        marginBottom: 16,
        fontSize: 14,
        fontWeight: "500",
        paddingHorizontal: 8,
    },
    expiringItem: {
        backgroundColor: "#f8fafc",
        padding: 16,
        borderRadius: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    expiringLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        flex: 1,
    },
    expiringIcon: {
        width: 48,
        height: 48,
        borderRadius: 16,
        backgroundColor: "#fee2e2",
        justifyContent: "center",
        alignItems: "center",
    },
    expiringBusiness: { fontWeight: "700", color: "#1e293b", fontSize: 14 },
    expiringDetails: {
        fontSize: 12,
        color: "#64748b",
        fontWeight: "500",
        marginTop: 2,
    },
    expiringArrow: {
        backgroundColor: "#fff",
        padding: 8,
        borderRadius: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    detailsBusinessCard: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 24,
        backgroundColor: "#f8fafc",
        padding: 16,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    detailsLogo: {
        width: 48,
        height: 48,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 16,
        shadowColor: "#6366f1",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 1,
    },
    detailsLogoText: { color: "#fff", fontWeight: "700", fontSize: 18 },
    detailsBusinessName: { fontWeight: "700", color: "#1e293b", fontSize: 16 },
    detailsBusinessAddress: {
        fontSize: 12,
        color: "#cbd5e1",
        fontWeight: "500",
        marginTop: 2,
    },
    detailsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 12,
        marginBottom: 24,
    },
    detailsItem: {
        backgroundColor: "#f8fafc",
        padding: 16,
        borderRadius: 16,
        width: "47%",
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    detailsLabel: {
        fontSize: 10,
        color: "#cbd5e1",
        fontWeight: "700",
        letterSpacing: 1,
        marginBottom: 4,
    },
    detailsValue: { fontWeight: "700", color: "#475569" },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        alignSelf: "flex-start",
    },
    statusExpiring: { backgroundColor: "#fee2e2" },
    statusExpired: { backgroundColor: "#fecaca" },
    statusActive: { backgroundColor: "#d1fae5" },
    statusPending: { backgroundColor: "#ffedd5" },
    statusText: { fontSize: 12, fontWeight: "700" },
    statusTextExpiring: { color: "#f43f5e" },
    statusTextExpired: { color: "#ef4444" },
    statusTextActive: { color: "#059669" },
    statusTextPending: { color: "#ea580c" },
    detailsButton: {
        paddingVertical: 16,
        borderRadius: 16,
        fontWeight: "700",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        alignItems: "center",
    },
    detailsButtonExpiring: { backgroundColor: "#f43f5e" },
    detailsButtonExpired: { backgroundColor: "#ef4444" },
    detailsButtonActive: { backgroundColor: "#1e293b" },
    detailsButtonPending: { backgroundColor: "#fb923c" },
    detailsButtonText: { color: "#fff", fontWeight: "700", fontSize: 16 },
    formToggle: {
        backgroundColor: "#f1f5f9",
        padding: 4,
        borderRadius: 16,
        flexDirection: "row",
        marginBottom: 24,
    },
    toggleButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: "center",
    },
    toggleButtonActive: {
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    toggleText: { fontSize: 14, fontWeight: "600", color: "#64748b" },
    toggleTextActive: { color: "#1e293b", fontWeight: "700" },
    input: {
        backgroundColor: "#f8fafc",
        padding: 16,
        borderRadius: 12,
        fontSize: 14,
        fontWeight: "500",
        color: "#1e293b",
        marginBottom: 16,
    },
    inputPlaceholder: { color: "#94a3b8" },
    fuelTypeGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 12,
        marginBottom: 16,
    },
    fuelButton: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        width: "47%",
        alignItems: "center",
    },
    fuelButtonActive: { borderColor: "#181818", backgroundColor: "#f8fafc" },
    fuelText: { fontSize: 12, fontWeight: "700", color: "#cbd5e1" },
    fuelTextActive: { color: "#181818" },
    submitButton: {
        backgroundColor: "#181818",
        paddingVertical: 16,
        borderRadius: 30,
        alignItems: "center",
        marginTop: 0,
        flexDirection: "row",
        justifyContent: "center",
    },
    submitButtonDisabled: {
        backgroundColor: "#cbd5e1",
    },
    submitButtonText: { color: "#fff", fontWeight: "700", fontSize: 16 },

    // New styles for multi-step Add Utility modal
    inputGroup: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: "700",
        color: "#1e293b",
        marginBottom: 8,
        marginLeft: 4,
    },
    businessList: {
        gap: 8,
    },
    businessOption: {
        flexDirection: "row",
        alignItems: "center",
        padding: 16,
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    businessOptionActive: {
        borderColor: "#6366f1",
        backgroundColor: "#eef2ff",
    },
    businessOptionLogo: {
        width: 40,
        height: 40,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    businessOptionLogoText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "700",
    },
    businessOptionName: {
        flex: 1,
        fontSize: 14,
        fontWeight: "600",
        color: "#64748b",
    },
    businessOptionNameActive: {
        color: "#1e293b",
    },
    optionsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    optionButton: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 20,
        backgroundColor: "#f8fafc",
    },
    optionButtonActive: {
        backgroundColor: "#181818",
    },
    optionText: {
        fontSize: 13,
        fontWeight: "500",
        color: "#64748b",
    },
    optionTextActive: {
        color: "#ffffff",
    },
    expiryList: {
        gap: 8,
    },
    expiryOption: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 14,
        backgroundColor: "#f8fafc",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    expiryOptionActive: {
        borderColor: "#181818",
        borderWidth: 1,
        borderStyle: "dashed",
        backgroundColor: "#f8fafc",
    },
    expiryOptionText: {
        fontSize: 14,
        fontWeight: "500",
        color: "#64748b",
    },
    expiryOptionTextActive: {
        color: "#181818",
        fontWeight: "600",
    },

    // Step indicator styles
    stepIndicator: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 8,
        paddingVertical: 12,
        paddingHorizontal: 24,
    },
    stepDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: "#e2e8f0",
    },
    stepDotActive: {
        width: 24,
        backgroundColor: "#6366f1",
    },
    stepDotCompleted: {
        backgroundColor: "#6366f1",
    },

    // Sheet body content styles
    sheetBodyContent: {
        paddingBottom: 24,
    },

    // Dropdown styles
    dropdown: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: "#f8fafc",
        padding: 16,
        borderRadius: 12,
    },
    dropdownText: {
        fontSize: 15,
        fontWeight: "700",
        color: "#181818",
    },
    dropdownPlaceholder: {
        color: "#94a3b8",
        fontWeight: "700",
    },
    dropdownList: {
        marginTop: 8,
        backgroundColor: "#fff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        overflow: "hidden",
        maxHeight: 250,
    },
    dropdownItem: {
        flexDirection: "row",
        alignItems: "center",
        padding: 14,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    dropdownItemActive: {
        backgroundColor: "#eef2ff",
    },
    dropdownItemLogo: {
        width: 32,
        height: 32,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    dropdownItemLogoText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "700",
    },
    dropdownItemText: {
        fontSize: 15,
        fontWeight: "700",
        color: "#64748b",
    },
    dropdownItemTextActive: {
        color: "#181818",
        fontWeight: "800",
    },

    // Button container
    buttonContainer: {
        marginTop: 0,
        paddingBottom: 8,
    },

    // Loading state
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingBottom: 100,
    },
    loadingText: {
        marginTop: 16,
        fontSize: 14,
        fontWeight: "500",
        color: "#94a3b8",
    },

    // Empty state
    emptyState: {
        alignItems: "center",
        paddingVertical: 48,
        paddingHorizontal: 32,
        marginHorizontal: 24,
        marginTop: 8,
        backgroundColor: "#fff",
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    emptyStateTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#1e293b",
        marginTop: 16,
    },
    emptyStateText: {
        fontSize: 14,
        fontWeight: "400",
        color: "#94a3b8",
        textAlign: "center",
        marginTop: 8,
        lineHeight: 20,
    },
    // Dashboard Slider Styles
    sliderWrapper: {
        marginVertical: 10,
    },
    sliderContainer: {
        paddingHorizontal: 20,
    },
    slideFrame: {
        width: width - 40,
        marginRight: 20,
    },
    widgetCard: {
        borderRadius: 30,
        height: 180,
        padding: 24,
        position: 'relative',
        overflow: 'hidden',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.15,
        shadowRadius: 15,
        elevation: 8,
    },
    widgetContent: {
        flex: 1,
        zIndex: 2,
    },
    widgetLabel: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 20,
        alignSelf: 'flex-start',
        marginBottom: 12,
    },
    widgetLabelText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    widgetTitle: {
        color: '#fff',
        fontSize: 24,
        fontWeight: '800',
        marginBottom: 8,
    },
    widgetDesc: {
        color: 'rgba(255,255,255,0.9)',
        fontSize: 14,
        lineHeight: 20,
        width: '70%',
    },
    widgetIconWrap: {
        position: 'absolute',
        right: -10,
        bottom: -10,
        zIndex: 1,
    },
    widgetDecor1: {
        position: 'absolute',
        top: -20,
        right: -20,
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    widgetDecor2: {
        position: 'absolute',
        bottom: -30,
        left: -10,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    pagination: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 15,
    },
    dot: {
        height: 6,
        borderRadius: 3,
        marginHorizontal: 3,
    },
    activeDot: {
        width: 20,
        backgroundColor: '#8b5cf6',
    },
    inactiveDot: {
        width: 6,
        backgroundColor: '#cbd5e1',
    },
    filterHeaderContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 24,
        paddingTop: 16,
        paddingBottom: 24,
    },
    filterSelector: {
        flex: 1,
        marginRight: 16,
    },
    filterLabel: {
        fontSize: 11,
        fontWeight: "700",
        color: "#94a3b8",
        marginBottom: 4,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    filterValueContainer: {
        flexDirection: "row",
        alignItems: "center",
    },
    filterValueText: {
        fontSize: 18,
        fontWeight: "800",
        color: "#181818",
    },
    filterChevron: {
        marginLeft: 6,
        marginTop: 2,
    },
    sheetFilterItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 16,
        borderRadius: 16,
        marginBottom: 8,
        backgroundColor: "#f8fafc",
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    sheetFilterItemActive: {
        backgroundColor: "#f8fafc",
        borderColor: "#181818",
    },
    sheetFilterItemText: {
        fontSize: 15,
        fontWeight: "600",
        color: "#64748b",
    },
    sheetFilterItemTextActive: {
        color: "#181818",
        fontWeight: "700",
    },
    siteBusinessBadge: {
        fontSize: 12,
        fontWeight: "600",
        color: "#94a3b8",
        marginTop: 2,
    },
});
